DEV Release of version 1.1.11-dev

diff --git a/radiomanager-cli b/radiomanager-cli
--- a/radiomanager-cli
+++ b/radiomanager-cli
@@ -8,7 +8,7 @@
 # ! swagger-codegen (https://github.com/swagger-api/swagger-codegen)
 # ! FROM SWAGGER SPECIFICATION IN JSON.
 # !
-# ! Generated on: 2018-11-07T11:21:18.399+01:00
+# ! Generated on: 2019-02-01T15:41:55.138+01:00
 # !
 # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
@@ -205,8 +205,10 @@ operation_parameters_minimum_occurrences["listItems:::limit"]=0
 operation_parameters_minimum_occurrences["listItems:::order-by"]=0
 operation_parameters_minimum_occurrences["listItems:::order-direction"]=0
 operation_parameters_minimum_occurrences["listItems:::_external_station_id"]=0
+operation_parameters_minimum_occurrences["playlistPostMerge:::data"]=0
 operation_parameters_minimum_occurrences["playlistPostStructure:::data"]=0
 operation_parameters_minimum_occurrences["playlistPostTiming:::data"]=0
+operation_parameters_minimum_occurrences["stopCurrentItem:::data"]=0
 operation_parameters_minimum_occurrences["updateItemById:::id"]=1
 operation_parameters_minimum_occurrences["updateItemById:::data"]=0
 operation_parameters_minimum_occurrences["getModelTypeById:::id"]=1
@@ -411,8 +413,10 @@ operation_parameters_maximum_occurrences["listItems:::limit"]=0
 operation_parameters_maximum_occurrences["listItems:::order-by"]=0
 operation_parameters_maximum_occurrences["listItems:::order-direction"]=0
 operation_parameters_maximum_occurrences["listItems:::_external_station_id"]=0
+operation_parameters_maximum_occurrences["playlistPostMerge:::data"]=0
 operation_parameters_maximum_occurrences["playlistPostStructure:::data"]=0
 operation_parameters_maximum_occurrences["playlistPostTiming:::data"]=0
+operation_parameters_maximum_occurrences["stopCurrentItem:::data"]=0
 operation_parameters_maximum_occurrences["updateItemById:::id"]=0
 operation_parameters_maximum_occurrences["updateItemById:::data"]=0
 operation_parameters_maximum_occurrences["getModelTypeById:::id"]=0
@@ -614,8 +618,10 @@ operation_parameters_collection_type["listItems:::limit"]=""
 operation_parameters_collection_type["listItems:::order-by"]=""
 operation_parameters_collection_type["listItems:::order-direction"]=""
 operation_parameters_collection_type["listItems:::_external_station_id"]=""
+operation_parameters_collection_type["playlistPostMerge:::data"]=""
 operation_parameters_collection_type["playlistPostStructure:::data"]=""
 operation_parameters_collection_type["playlistPostTiming:::data"]=""
+operation_parameters_collection_type["stopCurrentItem:::data"]=""
 operation_parameters_collection_type["updateItemById:::id"]=""
 operation_parameters_collection_type["updateItemById:::data"]=""
 operation_parameters_collection_type["getModelTypeById:::id"]=""
@@ -1143,8 +1149,10 @@ read -r -d '' ops <<EOF
   ${CYAN}getCurrentItem${OFF};Get current Item (AUTH)
   ${CYAN}getItemById${OFF};Get extended item details by ID. (AUTH)
   ${CYAN}listItems${OFF};Get a list of all the items currently in your station. (AUTH)
+  ${CYAN}playlistPostMerge${OFF};Post a playlist, do not remove previously imported items (AUTH)
   ${CYAN}playlistPostStructure${OFF};Post a playlist, keep current structure (AUTH)
   ${CYAN}playlistPostTiming${OFF};Post a playlist (AUTH)
+  ${CYAN}stopCurrentItem${OFF};Stop an Item (AUTH)
   ${CYAN}updateItemById${OFF};Update extended item details by ID. (AUTH)
 EOF
 echo "  $ops" | column -t -s ';'
@@ -2267,6 +2275,29 @@ print_listItems_help() {
 }
 ##############################################################################
 #
+# Print help for playlistPostMerge operation
+#
+##############################################################################
+print_playlistPostMerge_help() {
+    echo ""
+    echo -e "${BOLD}${WHITE}playlistPostMerge - Post a playlist, do not remove previously imported items${OFF}${BLUE}(AUTH - HEADER)${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e ""
+    echo -e "Post a playlist, do not remove previously imported items" | paste -sd' ' | fold -sw 80
+    echo -e ""
+    echo -e "${BOLD}${WHITE}Parameters${OFF}"
+    echo -e "  * ${GREEN}body${OFF} ${BLUE}[application/json]${OFF}${OFF} - Data *(Optional)*" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e ""
+    echo ""
+    echo -e "${BOLD}${WHITE}Responses${OFF}"
+    code=202
+    echo -e "${result_color_table[${code:0:1}]}  202;success${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+    code=403
+    echo -e "${result_color_table[${code:0:1}]}  403;Forbidden${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+    code=422
+    echo -e "${result_color_table[${code:0:1}]}  422;Unprocessable Entity${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+}
+##############################################################################
+#
 # Print help for playlistPostStructure operation
 #
 ##############################################################################
@@ -2310,6 +2341,33 @@ print_playlistPostTiming_help() {
     echo -e "${result_color_table[${code:0:1}]}  403;Forbidden${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
     code=422
     echo -e "${result_color_table[${code:0:1}]}  422;Unprocessable Entity${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+}
+##############################################################################
+#
+# Print help for stopCurrentItem operation
+#
+##############################################################################
+print_stopCurrentItem_help() {
+    echo ""
+    echo -e "${BOLD}${WHITE}stopCurrentItem - Stop an Item${OFF}${BLUE}(AUTH - HEADER)${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e ""
+    echo -e "Set a current playing or specific item on played" | paste -sd' ' | fold -sw 80
+    echo -e ""
+    echo -e "${BOLD}${WHITE}Parameters${OFF}"
+    echo -e "  * ${GREEN}body${OFF} ${BLUE}[application/json]${OFF}${OFF} - Data *(Optional)*" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e ""
+    echo ""
+    echo -e "${BOLD}${WHITE}Responses${OFF}"
+    code=200
+    echo -e "${result_color_table[${code:0:1}]}  200;Successfully stopped item${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+    code=403
+    echo -e "${result_color_table[${code:0:1}]}  403;Forbidden${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+    code=404
+    echo -e "${result_color_table[${code:0:1}]}  404;Not Found${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+    code=422
+    echo -e "${result_color_table[${code:0:1}]}  422;Unprocessable Entity${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+    code=429
+    echo -e "${result_color_table[${code:0:1}]}  429;Too Many Requests${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
 }
 ##############################################################################
 #
@@ -4774,6 +4832,84 @@ call_listItems() {
 
 ##############################################################################
 #
+# Call playlistPostMerge operation
+#
+##############################################################################
+call_playlistPostMerge() {
+    # ignore error about 'path_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local path_parameter_names=()
+    # ignore error about 'query_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local query_parameter_names=(  )
+    local path
+
+    if ! path=$(build_request_path "/api/v2/items/playlist/merge" path_parameter_names query_parameter_names); then
+        ERROR_MSG=$path
+        exit 1
+    fi
+    local method="POST"
+    local headers_curl
+    headers_curl=$(header_arguments_to_curl)
+    if [[ -n $header_accept ]]; then
+        headers_curl="${headers_curl} -H 'Accept: ${header_accept}'"
+    fi
+
+    local basic_auth_option=""
+    if [[ -n $basic_auth_credential ]]; then
+        basic_auth_option="-u ${basic_auth_credential}"
+    fi
+    local body_json_curl=""
+
+    #
+    # Check if the user provided 'Content-type' headers in the
+    # command line. If not try to set them based on the Swagger specification
+    # if values produces and consumes are defined unambigously
+    #
+    if [[ -z $header_content_type ]]; then
+        header_content_type="application/json"
+    fi
+
+
+    if [[ -z $header_content_type && "$force" = false ]]; then
+        :
+        echo "ERROR: Request's content-type not specified!!!"
+        echo "This operation expects content-type in one of the following formats:"
+        echo -e "\\t- application/json"
+        echo ""
+        echo "Use '--content-type' to set proper content type"
+        exit 1
+    else
+        headers_curl="${headers_curl} -H 'Content-type: ${header_content_type}'"
+    fi
+
+
+    #
+    # If we have received some body content over pipe, pass it from the
+    # temporary file to cURL
+    #
+    if [[ -n $body_content_temp_file ]]; then
+        if [[ "$print_curl" = true ]]; then
+            echo "cat ${body_content_temp_file} | curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\" -d @-"
+        else
+            eval "cat ${body_content_temp_file} | curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\" -d @-"
+        fi
+        rm "${body_content_temp_file}"
+    #
+    # If not, try to build the content body from arguments KEY==VALUE and KEY:=VALUE
+    #
+    else
+        body_json_curl=$(body_parameters_to_json)
+        if [[ "$print_curl" = true ]]; then
+            echo "curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} ${body_json_curl} \"${host}${path}\""
+        else
+            eval "curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} ${body_json_curl} \"${host}${path}\""
+        fi
+    fi
+}
+
+##############################################################################
+#
 # Call playlistPostStructure operation
 #
 ##############################################################################
@@ -4865,6 +5001,84 @@ call_playlistPostTiming() {
     local path
 
     if ! path=$(build_request_path "/api/v2/items/playlist/timing" path_parameter_names query_parameter_names); then
+        ERROR_MSG=$path
+        exit 1
+    fi
+    local method="POST"
+    local headers_curl
+    headers_curl=$(header_arguments_to_curl)
+    if [[ -n $header_accept ]]; then
+        headers_curl="${headers_curl} -H 'Accept: ${header_accept}'"
+    fi
+
+    local basic_auth_option=""
+    if [[ -n $basic_auth_credential ]]; then
+        basic_auth_option="-u ${basic_auth_credential}"
+    fi
+    local body_json_curl=""
+
+    #
+    # Check if the user provided 'Content-type' headers in the
+    # command line. If not try to set them based on the Swagger specification
+    # if values produces and consumes are defined unambigously
+    #
+    if [[ -z $header_content_type ]]; then
+        header_content_type="application/json"
+    fi
+
+
+    if [[ -z $header_content_type && "$force" = false ]]; then
+        :
+        echo "ERROR: Request's content-type not specified!!!"
+        echo "This operation expects content-type in one of the following formats:"
+        echo -e "\\t- application/json"
+        echo ""
+        echo "Use '--content-type' to set proper content type"
+        exit 1
+    else
+        headers_curl="${headers_curl} -H 'Content-type: ${header_content_type}'"
+    fi
+
+
+    #
+    # If we have received some body content over pipe, pass it from the
+    # temporary file to cURL
+    #
+    if [[ -n $body_content_temp_file ]]; then
+        if [[ "$print_curl" = true ]]; then
+            echo "cat ${body_content_temp_file} | curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\" -d @-"
+        else
+            eval "cat ${body_content_temp_file} | curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\" -d @-"
+        fi
+        rm "${body_content_temp_file}"
+    #
+    # If not, try to build the content body from arguments KEY==VALUE and KEY:=VALUE
+    #
+    else
+        body_json_curl=$(body_parameters_to_json)
+        if [[ "$print_curl" = true ]]; then
+            echo "curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} ${body_json_curl} \"${host}${path}\""
+        else
+            eval "curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} ${body_json_curl} \"${host}${path}\""
+        fi
+    fi
+}
+
+##############################################################################
+#
+# Call stopCurrentItem operation
+#
+##############################################################################
+call_stopCurrentItem() {
+    # ignore error about 'path_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local path_parameter_names=()
+    # ignore error about 'query_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local query_parameter_names=(  )
+    local path
+
+    if ! path=$(build_request_path "/api/v2/items/stopcurrent" path_parameter_names query_parameter_names); then
         ERROR_MSG=$path
         exit 1
     fi
@@ -6627,11 +6841,17 @@ case $key in
     listItems)
     operation="listItems"
     ;;
+    playlistPostMerge)
+    operation="playlistPostMerge"
+    ;;
     playlistPostStructure)
     operation="playlistPostStructure"
     ;;
     playlistPostTiming)
     operation="playlistPostTiming"
+    ;;
+    stopCurrentItem)
+    operation="stopCurrentItem"
     ;;
     updateItemById)
     operation="updateItemById"
@@ -6909,11 +7129,17 @@ case $operation in
     listItems)
     call_listItems
     ;;
+    playlistPostMerge)
+    call_playlistPostMerge
+    ;;
     playlistPostStructure)
     call_playlistPostStructure
     ;;
     playlistPostTiming)
     call_playlistPostTiming
+    ;;
+    stopCurrentItem)
+    call_stopCurrentItem
     ;;
     updateItemById)
     call_updateItemById
